{
  "id": "12311947",
  "name": "0.3.2",
  "description": "",
  "date": "2006-06-09",
  "version": "0.3.2",
  "module": "",
  "lastUpdated": 1633087976504,
  "type": "release",
  "_links": {
    "self": {
      "href": "https://apis.danklco.com/apache-release-info/HADOOP/12311947"
    },
    "jira": {
      "href": "https://issues.apache.org/jira/browse/HADOOP/fixforversion/12311947"
    },
    "project": {
      "href": "https://apis.danklco.com/apache-release-info/HADOOP"
    }
  },
  "releaseNotes": "Release Notes - Hadoop Common - Version 0.3.2",
  "_embedded": {
    "issues": [
      {
        "issue": "HADOOP-240",
        "title": "namenode should not log failed mkdirs at warning level",
        "type": "Bug",
        "_links": {
          "release": {
            "href": "https://apis.danklco.com/apache-release-info/HADOOP/12311947"
          },
          "jira": {
            "href": "https://issues.apache.org/jira/browse/HADOOP-240"
          }
        }
      },
      {
        "issue": "HADOOP-242",
        "title": "job fails because of \"No valid local directories in property: \" exception",
        "type": "Bug",
        "_links": {
          "release": {
            "href": "https://apis.danklco.com/apache-release-info/HADOOP/12311947"
          },
          "jira": {
            "href": "https://issues.apache.org/jira/browse/HADOOP-242"
          }
        }
      },
      {
        "issue": "HADOOP-277",
        "title": "Race condition in Configuration.getLocalPath()",
        "type": "Bug",
        "_links": {
          "release": {
            "href": "https://apis.danklco.com/apache-release-info/HADOOP/12311947"
          },
          "jira": {
            "href": "https://issues.apache.org/jira/browse/HADOOP-277"
          }
        }
      },
      {
        "issue": "HADOOP-280",
        "title": "AllTestDriver has incorrect class name for DistributedFSCheck test",
        "type": "Bug",
        "_links": {
          "release": {
            "href": "https://apis.danklco.com/apache-release-info/HADOOP/12311947"
          },
          "jira": {
            "href": "https://issues.apache.org/jira/browse/HADOOP-280"
          }
        }
      },
      {
        "issue": "HADOOP-282",
        "title": "the datanode crashes if it starts before the namenode",
        "type": "Bug",
        "_links": {
          "release": {
            "href": "https://apis.danklco.com/apache-release-info/HADOOP/12311947"
          },
          "jira": {
            "href": "https://issues.apache.org/jira/browse/HADOOP-282"
          }
        }
      },
      {
        "issue": "HADOOP-284",
        "title": "dfs timeout on open",
        "type": "Bug",
        "_links": {
          "release": {
            "href": "https://apis.danklco.com/apache-release-info/HADOOP/12311947"
          },
          "jira": {
            "href": "https://issues.apache.org/jira/browse/HADOOP-284"
          }
        }
      },
      {
        "issue": "HADOOP-285",
        "title": "Data nodes cannot re-join the cluster once connection is lost",
        "type": "Bug",
        "_links": {
          "release": {
            "href": "https://apis.danklco.com/apache-release-info/HADOOP/12311947"
          },
          "jira": {
            "href": "https://issues.apache.org/jira/browse/HADOOP-285"
          }
        }
      },
      {
        "issue": "HADOOP-289",
        "title": "Datanodes need to catch SocketTimeoutException and UnregisteredDatanodeException",
        "type": "Bug",
        "_links": {
          "release": {
            "href": "https://apis.danklco.com/apache-release-info/HADOOP/12311947"
          },
          "jira": {
            "href": "https://issues.apache.org/jira/browse/HADOOP-289"
          }
        }
      },
      {
        "issue": "HADOOP-292",
        "title": "hadoop dfs commands should not output superfluous data to stdout",
        "type": "Bug",
        "_links": {
          "release": {
            "href": "https://apis.danklco.com/apache-release-info/HADOOP/12311947"
          },
          "jira": {
            "href": "https://issues.apache.org/jira/browse/HADOOP-292"
          }
        }
      },
      {
        "issue": "HADOOP-294",
        "title": "dfs client error retries aren't happening (already being created and not replicated yet)",
        "type": "Bug",
        "_links": {
          "release": {
            "href": "https://apis.danklco.com/apache-release-info/HADOOP/12311947"
          },
          "jira": {
            "href": "https://issues.apache.org/jira/browse/HADOOP-294"
          }
        }
      },
      {
        "issue": "HADOOP-275",
        "title": "log4j changes for hadoopStreaming",
        "type": "New Feature",
        "_links": {
          "release": {
            "href": "https://apis.danklco.com/apache-release-info/HADOOP/12311947"
          },
          "jira": {
            "href": "https://issues.apache.org/jira/browse/HADOOP-275"
          }
        }
      },
      {
        "issue": "HADOOP-269",
        "title": "add FAQ to Wiki",
        "type": "Improvement",
        "_links": {
          "release": {
            "href": "https://apis.danklco.com/apache-release-info/HADOOP/12311947"
          },
          "jira": {
            "href": "https://issues.apache.org/jira/browse/HADOOP-269"
          }
        }
      },
      {
        "issue": "HADOOP-279",
        "title": "running without the hadoop script causes warnings about log4j not being configured correctly",
        "type": "Improvement",
        "_links": {
          "release": {
            "href": "https://apis.danklco.com/apache-release-info/HADOOP/12311947"
          },
          "jira": {
            "href": "https://issues.apache.org/jira/browse/HADOOP-279"
          }
        }
      }
    ]
  }
}